version: '3'

services:
  web: 
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/
    links:
      - lecture:lecture
    ports:
      - "8080:80"
  
  lecture:
    build: ./server
    volumes:
      - ./server:/opt/lecture
    environment:
      - NODE_ENV=production

    ports:
      - "5000"
   