version: '3'

services:
  web: 
    build: ./nginx
    links:
      - lecture:lecture
    ports:
      - "80:80"
  
  lecture:
    build: ./server
    volumes:
      - ./server:/opt/lecture
    environment:
      - NODE_ENV=production
    ports:
      - "3000"
    links:
      - mongo

  mongo:
    image: mongo
    ports: 
      - 27017:27017